### ISSUE TITLE
Transferring crates.io ownership to gtk-rs

### ISSUE THREAD

**Issue by GuillaumeGomez** [Emoun/graphene#8]
Hi,

You are the current owner of the crate "graphene" on crates.io. Do you think you could transfer "graphene" name to https://github.com/gtk-rs? For now we use "graphene-rs" but it's not great. If you don't mind transferring the crate name to us, you can do it from https://crates.io/crates/graphene/settings. Either me or @sdroege would be perfect, then we can handle things on our side.

Thanks in advance!

**Comment by Emoun** [comment]
Hi,

Sorry, but I'm going to have to say no. I still intend to use this crate.

**Comment by GuillaumeGomez** [comment]
Ok, thanks for the quick answer in any case!
